meta_product_name: "City Pulse"
meta_title: "Pour s'impliquer dans sa ville !"
meta_description: "City Pulse permet de proposer ses idées à sa Mairie, ou a voter pour les idées des autres citoyens!"
meta_image: "cover.png"
